### ISSUE TITLE
change default connect string parameter 

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/gdoc-api#12]
https://github.com/dag-hammarskjold-library/gdoc-api/blob/a954ddf5dab2063d9c53500ab69bc6c48928637a/gdoc_api/scripts/gdoc_dlx.py#L31

New parameter name = prodISSU-admin-connect-string

Also we need to add a parameter for database name, e.g., `DB.connect(Config.connect_string, database=Config.dbname)`
```[tasklist]
### Tasks
- [ ] Update connect-string in gdoc_dlx.py
- [ ] Update connect-string in gdoc_dlx_retro.py
- [ ] Add databse name to gdoc_dlx.py
- [ ] Add database name to gdoc_dlx_retro.py
```
